version: '3'
services:
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres_univercity
    ports:
      - '5432:5432'
    restart: always
    command: postgres -c listen_addresses='*'
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env 
    container_name: api_univercity

volumes:
  postgres-db:

