version: '3'
services:
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres_univercity
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:

