"""create group and course

Revision ID: 19d6e16b11c2
Revises: 69646bd4200b
Create Date: 2023-06-09 23:56:35.392755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19d6e16b11c2"
down_revision = "69646bd4200b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
