"""create group and course

Revision ID: 69646bd4200b
Revises: ec3df8186d1b
Create Date: 2023-06-09 23:32:58.875226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69646bd4200b'
down_revision = 'ec3df8186d1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
