"""move to another ierarchy

Revision ID: b4160a12ded7
Revises: e301e7842672
Create Date: 2023-06-13 00:09:00.448169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4160a12ded7'
down_revision = 'e301e7842672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
