"""teacher_course ubique constraint

Revision ID: cb35db505a3d
Revises: e647e316c34a
Create Date: 2023-06-12 23:40:16.871257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb35db505a3d'
down_revision = 'e647e316c34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
