"""teacher_course ubique constraint

Revision ID: e647e316c34a
Revises: e81ee9c41c34
Create Date: 2023-06-12 08:56:04.457185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e647e316c34a'
down_revision = 'e81ee9c41c34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'visitors', ['passport_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='unique')
    # ### end Alembic commands ###
