"""create group and course_2

Revision ID: e81ee9c41c34
Revises: 19d6e16b11c2
Create Date: 2023-06-10 00:05:26.865184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e81ee9c41c34"
down_revision = "19d6e16b11c2"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "teacher_course",
        sa.Column("teacher_id", sa.Integer(), sa.ForeignKey("teachers.id")),
        sa.Column("course_id", sa.Integer(), sa.ForeignKey("courses.id")),
        sa.UniqueConstraint(
            "teacher_id", "course_id", name="uq_teacher_course"
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
