"""course grade unique constraint

Revision ID: f12591b0b7b5
Revises: 0bfb579e5d86
Create Date: 2023-06-14 20:20:44.458004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12591b0b7b5'
down_revision = '0bfb579e5d86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
